### ISSUE TITLE
Is "owner" a special role?

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/gateway-module#5]
@superdweebie thanks for the recent updates.

Is `owner` a special / reserved role? I'm guessing it is, but just wanted to get your input.

**Comment by superdweebie** [comment]
It is if you enable shard's `owner` extension (see http://zoopcommerce.github.io/shard/extensions.html#owner). If you're not using that extension, then it is not reserved/special.

**Comment by joshystuart** [comment]
Awesome. Thanks!
